// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pajshbjchughbjzdozla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhanNoYmpjaHVnaGJqemRvemxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjQ0NTQsImV4cCI6MjA2MTAwMDQ1NH0.pITLK_f6e2PFFXVy_uFM0ok825-LlBNa4ZZ6sz2Lcvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);